name: oduczanie
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - cudatoolkit
  - jupyter
  - cloudpickle
  - python==3.11
  - torchmetrics==1.3.1
  - numpy==2.2.6
  - pillow==11.2.1
  - tqdm==4.67.1
  - matplotlib==3.10.3
  - seaborn==0.13.2
  - gdown==4.7.1
  - scikit-learn=1.4.2
  - scikit-image=0.25.2
  - pip:
    - torch==2.6.0 --index-url https://download.pytorch.org/whl/cu126 
    - torchvision --index-url https://download.pytorch.org/whl/cu126