name: inpainting
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - cudatoolkit
  - jupyter
  - cloudpickle
  - python==3.11
  - numpy==2.2.6
  - tqdm==4.67.1
  - matplotlib==3.10.3
  - scikit-learn=1.4.2
  - scikit-image=0.25.2
  - conda-forge::opencv=4.11.0
  - pip:
    - torch==2.6.0 --index-url https://download.pytorch.org/whl/cu126 
